### ISSUE TITLE
Concept Triage: Set-Up & System Architecture

### ISSUE THREAD

**Issue by D1no** [hundertschaft/flywheel#1]
Workspace Areas for integrated trunk based mono-repository structure.
  - assets
  - content
  - features
  - infrastructure
  - intelligence
  - notebooks
  - platform
  - policy
  - services

----

```[tasklist]
# To-Dos
- [x] Create monorepo scaffold as needed
- [x] #6
- [ ] Unblock End-to-End Type Safety / Storybook
```

----

## Assets
Stack: `Figma`, `Design Tokens`, `Markdown`, `i18n`, `Media Files`
Location for all content used within platform, application and external systems (i.e. design / corporate identity exports)
- [x] Move images from web app scaffold to assets and link back to `platform`

## Platform 
Stack: `pnpm`, `Node.js`, `TypeScript`, `React`, `Vite`, `Storybook`, `Playwright`
Location for all application code like apps, server and services as well as application test tooling.

- [x] Create `pnpm` or `nx` workspace for integrated application development workflows 
  - [x] Add library structure incl. outer bound workspaces like `assets/`
  - [x] Add `vite` based `react` app
  - [x] Separate into `ui` libs and link / inherit dependencies incl. `tsconfig.json`
- [ ] Create sample web app with interactions
  - [x] Prune boilerplate app scaffold
  - [x] Split app scaffold into `ui` libs with `shell` and design system
  - [ ] Add an interactive sample component that has delays (i.e. rating, mini-game, etc)
    - [ ] Rewrite component to be child first composable (best practice app architecture)
    - [ ] Introduce state manager like `xState` to illustrate event integration
  - [ ] Add basic ui analytics for app and user life cycle events
- [ ] Add Developer Experience Tooling
  - [x] Add `husky` pre-commit hooks
  - [x] Add `prettier` with dependency import sorting for code consistency
  - [x] Add `gitmoji` intention tags git msg hook
  - [x] Add in-code comment tags via `todo-tree`
  - [x] #2
    - [ ] Find solution to automatically sort React JSX properties for `xStyled` shorthands to sensibly groupe style and component properties
  - [x] #3
  - [x] #5
  - [ ] Add `wallaby` interactive test runner configured for mono repo structure (`storybook`, `playwright`)
- [ ] Add Test Runtime Tooling
  - [x] Add `storybook` for component and visual testing
    - [x] Add sample component stories
    - [x] Update storybook and add `.cache` to git ignore
    - [ ] Add sample story with storybook interaction test
  - [x] #7 
    - [ ] #8
    - [ ] #9

## Infrastructure
Stack: `kubernetes`, `argoCD`, `docker`, `gitOps`
Location for all dev, build and production environments incl. required services such as databases, systems and runners.

- [ ] Provision a "cloud neutral" bare metal self hosted example with Ubuntu Server running `kubernetes`
  - [x] Buy cheap dedicated server (likely kimsufi by OVH)
  - [x] Image server with `Ubuntu Server 22.04 LTS` and connect to DNS
  - [x] #4
  - [ ] Install `ArgoCD` to enable GitOps
    - [ ] Connect ArgoCD to GitHub Repository
  - [ ] Turn set-up process into repeatable IaC or post-installation script and add to repository

## Global
General items not limited to a particular work area.

- [ ] Validate and Add [SLSA Security Level](https://slsa.dev/) Badge
- [ ] Validate and Add [OpenSSF Scorecard](https://securityscorecards.dev/) Badge

**Comment by D1no** [comment]
Needs triage / Ideas

Add CI/CD via github actions and arc for local CI/CD actions sharing
https://youtu.be/Ugonll0e2Os

Add depandabot auto dependency upgrades and auto merging as soon as tests are in place

Add tilt.dev for "desk ready" one command Engineering environment

Consider x86 based docket setup for github codespaces (desk ready)

Add feature flag system along stack

Add neet.js server App scaffold

Create sample CQRS neet.js feature endpoint and combine with react hooks for lose coupling

Add Kafka via Red Panda for event sourcing
 - Add note about [Azure Event Hub](https://learn.microsoft.com/en-us/azure/event-hubs/azure-event-hubs-kafka-overview), a kafka compatible and managed cloud solution as to self managing data streaming is often not required.

Add Materialize for event / data projections

Add cerbos authentification data access policy layer

Add Mem Graph for real time graph analysis / analytics 

Add figma workspace with export page and design tokens

Add Kubernetes + ArgoCD deployment target

Add snyke security screening

Add and check `SLSA` 3-4 security compliance and add badge

Add Python data science environment, ray and/or dask

Add machine learning environment (likely TensorFlow)

Add sample machine learning implementation (idea: recommender system based on analytics)

**Comment by D1no** [comment]
Reading

- https://github.com/stakater-archive/tbd-cd-workflow
- https://github.com/stakater/developer-handbook/blob/master/content/git/tbd.md
